- packages/std/Cargo.lock
- packages/std/Cargo.toml
- packages/std/autotools.tg
- packages/std/bootstrap.tg
- packages/std/bootstrap/rust.tg
- packages/std/container.tg
- packages/std/env.tg
- packages/std/packages/env/Cargo.toml
- packages/std/packages/tgld/Cargo.toml
- packages/std/packages/tgld/src/main.rs
- packages/std/packages/wrapper/Cargo.toml
- packages/std/packages/wrapper/src/main.rs
- packages/std/packages/wrapper/src/manifest.rs
- packages/std/phases.tg
- packages/std/sdk.tg
- packages/std/sdk/dependencies.tg
- packages/std/sdk/proxy.tg
- packages/std/tangram.tg
- packages/std/utils.tg
- packages/std/wrap.tg
This PR introduces a breaking change to the types that comprise the wrapper manifest, as well as some additional changes:
* More judicious use of tg.target
* Consistent pattern in tg.Args.apply blocks
* Stop using serialize-only types for performing operations in `wrap.tg`
* As a consequence of above, avoid unnecessary conversions
* Remove unused crates from package workspace
* Linker proxy respects specified interpreters
* Linker proxy minimizes unnecessary references
* Linker proxy gained an option to produce a combined library directory. Disabled for now.
* Implement `std.wrap.unwrap()`/`tryUnwrap()`
* Corrected some error-handling cases
* Properly validate env values when converting to/from manifest
> fix!(std-wrap): refactor std.wrap() and linker proxy

- packages/openssl/tangram.tg.ts
The default behavior on `x86_64-linux` is to create a `lib64` directory for libraries, but on `aarch64-linux` and `darwin`, it just creates `lib`, which we prefer. This PR instead specifies `lib` during configuration, ensuring uniformity across supported systems.
> fix(openssl): prevent creating lib64 directory in output

- packages/acl/tangram.tg.ts
- packages/attr/tangram.tg.ts
- packages/autoconf/tangram.tg.ts
- packages/automake/tangram.tg.ts
- packages/bash/tangram.tg.ts
- packages/bc/tangram.tg.ts
- packages/bzip2/tangram.tg.ts
- packages/coreutils/tangram.tg.ts
- packages/file/tangram.tg.ts
- packages/flex/tangram.tg.ts
- packages/gcc/tangram.tg.ts
- packages/gettext/tangram.tg.ts
- packages/gperf/tangram.tg.ts
- packages/help2man/tangram.tg.ts
- packages/libcap/tangram.tg.ts
- packages/libseccomp/tangram.tg.ts
- packages/libxcrypt/tangram.tg.ts
- packages/perl/tangram.tg.ts
- packages/pkgconfig/tangram.tg.ts
- packages/std/assert.tg.ts
- packages/std/sdk/dependencies/bc.tg.ts
- packages/std/sdk/kernel_headers.tg.ts
- packages/std/utils.tg.ts
- packages/std/utils/attr.tg.ts
- packages/texinfo/tangram.tg.ts
- packages/zstd/tangram.tg.ts
This PR ensures all packages used inside `std` to bootstrap the toolchain have a corresponding package outside `std` for general use.
> feat: add post-std packages for all SDK dependencies

- packages/rust/Cargo.lock
- packages/rust/Cargo.toml
- packages/rust/proxy.tg.ts
- packages/rust/src/driver.sh
- packages/rust/src/main.rs
- packages/rust/tangram.tg.ts
- packages/rust/tests/hello-openssl/Cargo.lock
- packages/rust/tests/hello-openssl/src/main.rs
- packages/rust/tests/hello-world/Cargo.lock
- packages/rust/tests/hello-world/src/main.rs
- packages/std/Cargo.lock
- packages/std/Cargo.toml
- packages/std/packages/ld_proxy/src/main.rs
- packages/std/sdk.tg.ts
- packages/std/sdk/cmake.tg.ts
- packages/std/wrap/workspace.tg.ts
Roll forward the Tangram dependency, re-enable proxy tests.
* Implement `parallel` and `verbose` flags for `rust.build`
* Fix argument parsing logic
* Safer POSIX sh syntax
* Correct extern handling
* Use `Artifact::check_in` in `ld_proxy`
> fix(rust): restore rust proxy

- packages/std/assert.tg.ts
- packages/std/bootstrap.tg.ts
- packages/std/sdk.tg.ts
- packages/std/sdk/kernel_headers.tg.ts
- packages/std/sdk/llvm.tg.ts
- packages/std/sdk/proxy.tg.ts
- packages/std/tangram.tg.ts
- packages/std/utils.tg.ts
- packages/std/wrap.tg.ts
- packages/std/wrap/injection.tg.ts
This PR defines a more robust set of SDK tests, exercising some previously untested combinations of configuration options.  It also includes some cleanup and corrections in the macOS and LLVM code paths. Closes #20.
> feat(std/sdk): more complete SDK testing

- packages/bzip2/tangram.tg.ts
- packages/rust/Cargo.lock
- packages/rust/Cargo.toml
- packages/rust/src/main.rs
- packages/std/Cargo.lock
- packages/std/Cargo.toml
- packages/std/packages/wrapper/src/main.rs
- packages/std/sdk.tg.ts
- packages/std/sdk/llvm.tg.ts
- packages/std/sdk/proxy.tg.ts
- packages/std/tangram.tg.ts
- packages/std/utils.tg.ts
- packages/std/utils/bash.tg.ts
- packages/std/utils/bzip2.tg.ts
- packages/std/utils/file_cmds.tg.ts
- packages/std/utils/tar.tg.ts
- packages/std/utils/xz.tg.ts
- packages/std/wrap.tg.ts
This PR fixes outstanding issues in the SDK definition to restore producing the default environment on macOS.  It also fixes a bug where `std.wrap()` was not correctly re-wrapping already-wrapped executables.
> fix(std): macOS SDK

- packages/cmake/tangram.tg.ts
- packages/eslint/tangram.tg.ts
- packages/fzf/tangram.tg.ts
- packages/go/tangram.tg.ts
- packages/hyperfine/tangram.tg.ts
- packages/lz4/tangram.tg.ts
- packages/ncurses/tangram.tg.ts
- packages/nodejs/tangram.tg.ts
- packages/perl/tangram.tg.ts
- packages/postgresql/tangram.tg.ts
- packages/python/requirements.tg.ts
- packages/python/tangram.tg.ts
- packages/readline/tangram.tg.ts
- packages/rust/tangram.tg.ts
- packages/std/autotools.tg.ts
- packages/std/build.tg.ts
- packages/std/utils.tg.ts
This PR corrects the arguments accepted by `std.build`, dropping obsolete fields, and adds a `checksum` argument to the following interfaces which passes through to the underlying builder:
- `std.autotools.build`
- `cmake.build`
- `go.build`
- `node.build`
- `rust.build`
This closes #58.
Additionally, this PR includes fixes to `ncurses` and `readline`, finally allowing downstream packages to properly build against these dependencies using their `pkg-config` files. Closes #31.
Also includes new package definitions for `lz4` and `hyperfine`.
> feat: thread checksum argument through builders

- packages/std/sdk.tg.ts
- packages/std/sdk/llvm.tg.ts
- packages/std/sdk/proxy.tg.ts
- packages/std/utils/bash.tg.ts
- packages/std/wrap.tg.ts
This PR implements the `inPlace` option on `std.wrap` to specify how to handle executables that are already Tangram wrappers.  The default behavior is `inPlace: true`, producing a manifest with the executable from the original wrapper. Specify `inPlace: false` to create a manifest pointing to the original wrapper as the executable.
This change unbreaks the LLVM proxy env on Linux.
> feat(std/wrap): add inPlace option

- packages/binutils/tangram.tg.ts
- packages/gcc/tangram.tg.ts
- packages/gettext/tangram.tg.ts
- packages/glibc/tangram.tg.ts
- packages/icu/tangram.tg.ts
- packages/libffi/tangram.tg.ts
- packages/libxml2/tangram.tg.ts
- packages/linux/tangram.tg.ts
- packages/musl/musl_permission.patch
- packages/musl/tangram.tg.ts
- packages/pkgconfig/tangram.tg.ts
- packages/python/tangram.tg.ts
- packages/ripgrep/tangram.tg.ts
- packages/rust/tangram.tg.ts
- packages/std/assert.tg.ts
- packages/std/sdk.tg.ts
- packages/std/sdk/gcc/toolchain.tg.ts
- packages/std/sdk/kernel_headers.tg.ts
- packages/std/sdk/llvm.tg.ts
- packages/xz/tangram.tg.ts
- packages/zlib/tangram.tg.ts
This PR rolls up changes to support building the `testLlvm` target in the `demo` package on Linux, which builds all packages and transitive dependencies with `clang`/`lld`/`libc++`.
- Correct `gettext` wrapping
- Ensure `rust.build` can use `-lgcc`
- Add `std.sdk.canonicalTriple`
- Re-enable asserting multiple SDKs at once
- Disable PGO on Python when using LLVM on Linux until our build of compiler-rt supports this
- Prevent dropping `libm.so.1` from the library paths in `icu`
- Allow `zlib` to build shared libraries with clang/lld
Additionally, this change includes new package definitions for `binutils`, `musl`, `glibc`, `libxml2`, and `linux`.
> fix(demo): working LLVM demo

- packages/git/tangram.tg.ts
- packages/linux/tangram.tg.ts
- packages/rust/tangram.tg.ts
- packages/std/packages/ld_proxy/src/main.rs
- packages/std/sdk.tg.ts
- packages/std/sdk/binutils.tg.ts
- packages/std/sdk/gcc.tg.ts
- packages/std/sdk/git.tg.ts
- packages/std/sdk/kernel_headers.tg.ts
- packages/std/sdk/libc/glibc.tg.ts
- packages/std/sdk/llvm.tg.ts
- packages/std/sdk/llvm/cmake/Distribution-stage2.cmake
- packages/std/sdk/llvm/cmake/Distribution.cmake
- packages/std/sdk/llvm/ncurses.tg.ts
- packages/std/tangram.tg.ts
- packages/std/wrap/workspace.tg.ts
This PR improves the LLVM SDK build in the following ways:
- Performs a 2-stage bootstrapping build
- Utilizes CMake cache files instead of CLI arguments for most configuration
- Includes the `zlib` and `terminfo` dependencies, which were omitted previously due to build failures
- Utilizes the `distribution` build and install targets to minimize the installed components
- Performs the stage 2 build using LTO for increased performance at the cost of build time
- Performs the stage 2 build using `-gline-tables-only` for increased debugging information
- Reduces the supported target architectures to those required by Tangram
- Prunes superfluous configuration
- Includes `Tangram` in the version string for increased snazziness
- Version bumps: git 2.45.0, rust 1.78.0, linux headers 6.8.9, …
> refactor(std/sdk/llvm): 2-stage LLVM build with LTO

- packages/attr/tangram.tg.ts
- packages/bash/tangram.tg.ts
- packages/cmake/ninja.tg.ts
- packages/git/tangram.tg.ts
- packages/mold/tangram.tg.ts
- packages/pkgconfig/tangram.tg.ts
- packages/postgresql/tangram.tg.ts
- packages/std/autotools.tg.ts
- packages/std/sdk/cmake.tg.ts
- packages/std/sdk/ninja.tg.ts
- packages/zsh/tangram.tg.ts
This PR commits a handful of outstanding changes before rolling forward the repo to the new API.
- omit unused `.la` files which hardcode the output dir from `attr` install directory
- re-add `gettext` dependency to packages where it had been removed
- wrap `mold` top-level build function in a target
- fix pkg-config proxy to call main program with `exec`
- fix auto-detected SDK args
- add zsh package
- bump ninja to v1.12.1, postgres to v16.3
> chore: roll up pre-roll forward changes

- packages/pkgconfig/tangram.tg.ts
- packages/std/autotools.tg.ts
- packages/std/packages/ld_proxy/src/main.rs
- packages/std/tangram.tg.ts
- packages/std/utils/coreutils.tg.ts
- packages/std/utils/diffutils.tg.ts
- packages/std/utils/gawk.tg.ts
- packages/std/utils/make.tg.ts
- packages/std/utils/patch.tg.ts
- packages/std/utils/tar.tg.ts
This PR prevents the SDK from being referenced by the standard utils on macOS, greatly reducing the size of these outputs. Closes #70.
> fix(std): ensure SDK is not referenced in standard env

- packages/bzip2/bzip2_dylib_detect_os.patch
- packages/bzip2/tangram.tg.ts
- packages/sqlite/tangram.tg.ts
- packages/std/tangram.tg.ts
- packages/std/utils/bzip2.tg.ts
- packages/std/utils/bzip2_dylib_detect_os.patch
This PR augments the bzip2 build definitions to produce a shared dylib in addition to the static library on macOS, mirroring linux. Closes #56.
The first commit provides a working but suboptimal solution. Before merging, will address:
> feat(bzip2): build dylib on macOS

- packages/acl/tangram.tg.ts
- packages/attr/tangram.tg.ts
- packages/curl/tangram.tg.ts
- packages/fftw/tangram.tg.ts
- packages/findutils/tangram.tg.ts
- packages/gettext/tangram.tg.ts
- packages/icu/tangram.tg.ts
- packages/libcap/tangram.tg.ts
- packages/pcre2/tangram.tg.ts
- packages/postgresql/tangram.tg.ts
- packages/std/Cargo.lock
- packages/std/Cargo.toml
- packages/std/autotools.tg.ts
- packages/std/packages/ld_proxy/Cargo.toml
- packages/std/packages/ld_proxy/src/main.rs
- packages/std/sdk/binutils.tg.ts
- packages/std/sdk/cmake.tg.ts
- packages/std/sdk/gcc.tg.ts
- packages/std/sdk/kernel_headers.tg.ts
- packages/std/sdk/libc/glibc.tg.ts
- packages/std/sdk/llvm.tg.ts
- packages/std/sdk/proxy.tg.ts
- packages/std/utils/findutils.tg.ts
This PR updates the LD proxy to correctly produce wrappers which pull in libraries from library paths in the working build tree.
It additionally cleans up additional now-unnecessary post-processing for package builds which depended on this behavior: `curl`, `fftw`, `gettext`, `icu`, `libcap`, `postgresql`.
Additional fixes:
- Strip libtool archives by default from autotools builds, with option to retain
- Correct curl build
- More robust ld proxy tests
- findutils v4.10, GCC 14.2, binutils 2.43, linux 6.10.3, cmake 3.30.2
> fix(ld_proxy): correctly handle non-artifact library paths

- packages/rust/cargo.tg.ts
Adds a `buildInTree` option to mirror `std.autotools`, which copies the source into the mutable build tempdir instead of referring to the manifest in the readonly source.
> feat(rust/cargo): buildInTree

- packages/std/Cargo.lock
- packages/std/Cargo.toml
- packages/std/packages/strip_proxy/Cargo.toml
- packages/std/packages/strip_proxy/src/main.rs
Replace poor timestamp-based logic for creating tempdirs with the `tempfile` crate.
Closes #96.
> fix(std): fix tempdir creation in strip_proxy

- packages/cmake/tangram.ts
- packages/curl/tangram.ts
- packages/git/tangram.ts
- packages/libxml2/tangram.ts
- packages/linux/tangram.ts
- packages/mold/tangram.ts
- packages/python/tangram.ts
- packages/rust/cargo.tg.ts
- packages/rust/proxy/Cargo.lock
- packages/rust/proxy/Cargo.toml
- packages/rust/proxy/src/main.rs
- packages/std/Cargo.lock
- packages/std/Cargo.toml
- packages/std/packages/ld_proxy/src/main.rs
- packages/std/packages/std/lib.rs
- packages/std/packages/std/manifest.rs
- packages/std/packages/strip_proxy/src/main.rs
- packages/std/packages/wrapper/src/main.rs
- packages/std/sdk/cmake.tg.ts
- packages/std/sdk/kernel_headers.tg.ts
- packages/std/sdk/libc/musl.tg.ts
- packages/std/sdk/llvm.tg.ts
- packages/std/sdk/llvm/git.tg.ts
- packages/std/sdk/mold.tg.ts
- packages/std/sdk/proxy.tg.ts
- packages/std/tangram.ts
- packages/std/wrap.tg.ts
Reflects the change from [tangramdotdev/tangram#348](https://github.com/tangramdotdev/tangram/pull/348) through the packages repo. Closes #114.
> refactor: symlink target variant

- packages/rust/cargo.tg.ts
- packages/rust/tangram.ts
A change in `rustc` behavior caused the `-C linker=cc` flag to not correctly determine the appropriate `linker-flavor`, falling back to a broken linker on Linux. Using `gcc` instead of `cc` corrects this issue on both platforms.
> fix(rust): force correct linker-flavor inference

- packages/std/packages/ld_proxy/src/main.rs
- packages/std/sdk/proxy.tg.ts
- packages/std/tangram.ts
Adds a new default library path strategy `Isolate` which creates an individual directory for each required library. This reduces duplication when checking out artifacts.
> feat(ld_proxy): add Isolate option

- .github/workflows/tag.yml
Replace the compilation of Tangram with the install script.
> fix(automation): use user-facing Tangram installer

- packages/std/packages/ld_proxy/src/main.rs
- packages/std/tangram.ts
- packages/std/wrap.tg.ts
Previously, the ld proxy was always creating wrappers with the `wrapper` identity. This change now defaults to `executable` when the executable is dynamically linked, matching the behavior of `std.wrap()`.
Closes #131.
> fix(ld_proxy): correctly set wrapper identity

- packages/rust/proxy/Cargo.lock
- packages/std/Cargo.lock
- packages/std/packages/ld_proxy/src/main.rs
- packages/std/packages/wrapper/src/main.rs
- packages/std/tangram.ts
- packages/std/wrap.tg.ts
- rename LibraryPathStrategy, remove integer option
- decouple interpreter construction from manifest serialization
- expose `neededLibraries` for wrappers of dynamically linked executables
> refactor(std/wrap): rollup
